CREATE DATABASE IF NOT EXISTS `{{ MYSQL_DB_NAME }}`;
CREATE USER '{{ MYSQL_USERNAME }}'@'%' IDENTIFIED BY '{{ MYSQL_PASSWORD }}';
GRANT ALL PRIVILEGES ON `{{ MYSQL_DB_NAME }}`.* TO '{{ MYSQL_USERNAME }}'@'%';
FLUSH PRIVILEGES;